from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession
from typing import Optional
import json
from pydantic import BaseModel
from services.llm_service import LLMService

from apps.api.auth.dependencies import CurrentUser, get_current_user
from storage.db.db import get_db
from connectors.jira.jira_client import JiraClient

router = APIRouter(prefix="/pm", tags=["pm_dashboard"])

@router.get("/projects")
async def get_pm_projects(
    session: AsyncSession = Depends(get_db),
    user: CurrentUser = Depends(get_current_user),
):
    try:
        # Fetching directly from Jira Client (or we can query distinct 'project' from documents)
        client = JiraClient()
        projects = client.get_projects()
        
        return {
            "projects": [
                {
                    "key": p.get("key"), 
                    "name": p.get("name"),
                    "id": p.get("id"),
                    "avatar": p.get("avatarUrls", {}).get("48x48")
                } 
                for p in projects
            ]
        }
    except Exception as e:
        # Fallback to DB if live Jira connection fails
        res = await session.execute(text("SELECT DISTINCT metadata->>'project' as key FROM documents WHERE source='jira' AND metadata->>'project' IS NOT NULL"))
        projects = [{"key": row[0], "name": row[0]} for row in res.fetchall()]
        return {"projects": projects}


@router.get("/dashboard/stats")
async def get_pm_dashboard_stats(
    project_key: Optional[str] = None,
    session: AsyncSession = Depends(get_db),
    user: CurrentUser = Depends(get_current_user),
):
    # Base query for all Jira documents
    query = """
    SELECT 
        COUNT(id) as total_issues,
        COUNT(id) FILTER (WHERE metadata->>'statusCategory' = 'done') as done_issues,
        COUNT(id) FILTER (WHERE metadata->>'statusCategory' IN ('in progress', 'indeterminate')) as in_progress_issues,
        COUNT(id) FILTER (WHERE metadata->>'statusCategory' IN ('to do', 'new')) as todo_issues,
        COUNT(id) FILTER (WHERE metadata->>'priority' IN ('High', 'Highest')) as high_priority_issues
    FROM documents 
    WHERE source = 'jira'
    """
    
    params = {}
    if project_key:
        query += " AND (metadata->>'project_key' ILIKE :project_key OR metadata->>'project_key' ILIKE :project_key_br)"
        params["project_key"] = project_key
        params["project_key_br"] = f"[{project_key}]"


        
    res = await session.execute(text(query), params)
    row = res.mappings().first()
    
    if not row:
         return {
            "total_issues": 0, "done_issues": 0, 
            "in_progress_issues": 0, "todo_issues": 0, "high_priority_issues": 0,
            "completion_rate": 0
         }
         
    total = row["total_issues"] or 0
    done = row["done_issues"] or 0
    in_progress = row["in_progress_issues"] or 0
    todo = row["todo_issues"] or 0
    high_priority = row["high_priority_issues"] or 0
    
    completion_rate = round((done / total * 100), 2) if total > 0 else 0
    
    return {
        "total_issues": total,
        "done_issues": done,
        "in_progress_issues": in_progress,
        "todo_issues": todo,
        "high_priority_issues": high_priority,
        "completion_rate": completion_rate
    }
    
@router.get("/dashboard/risks")
async def get_pm_risks(
    project_key: Optional[str] = None,
    limit: int = 5,
    session: AsyncSession = Depends(get_db),
    user: CurrentUser = Depends(get_current_user),
):
    # Placeholder for risks generated by PM Digest background task
    # For now, we simulate pulling "ai_task_drafts" or "documents" that are labeled as risks
    # In full implementation, we can query a specific table for generated reports
    
    query = """
    SELECT 
        title, content, created_at
    FROM doc_drafts
    WHERE doc_type = 'pm_risk_report'
    """
    
    params = {}
    if project_key:
        query += " AND title LIKE :project_key"
        params["project_key"] = f"%[{project_key}]%"
        
    query += " ORDER BY created_at DESC LIMIT :limit"
    params["limit"] = limit
    
    res = await session.execute(text(query), params)
    rows = res.mappings().fetchall()
    
    risks = []
    for r in rows:
        risks.append({
            "title": r["title"],
            "summary": r["content"],
            "created_at": r["created_at"].isoformat() if r["created_at"] else None
        })
        
    # If no AI reports generated yet, send dummy data just for the UI
    if not risks:
        risks = [
            {
                "title": "Chưa có báo cáo AI",
                "summary": "Hệ thống tự động (PM Digest) chưa chạy cho dự án này. Báo cáo sẽ được tạo vào 8:00 AM Thứ Hai và Thứ Năm.",
                "created_at": None
            }
        ]
        
    return {"risks": risks}

@router.get("/dashboard/workload")
async def get_pm_workload(
    project_key: Optional[str] = None,
    session: AsyncSession = Depends(get_db),
    user: CurrentUser = Depends(get_current_user),
):
    query = """
    SELECT 
        COALESCE(metadata->'assignee'->>'displayName', 'Unassigned') as assignee,
        COALESCE(metadata->>'statusCategory', 'to do') as status,
        COUNT(*) as count
    FROM documents
    WHERE source = 'jira'
    """
    
    params = {}
    if project_key:
        query += " AND (metadata->>'project_key' ILIKE :project_key OR metadata->>'project_key' ILIKE :project_key_br)"
        params["project_key"] = project_key
        params["project_key_br"] = f"[{project_key}]"


        
    query += " GROUP BY 1, 2 ORDER BY count DESC"
    
    res = await session.execute(text(query), params)
    rows = res.mappings().fetchall()
    
    # Structure data for Chart.js: { assignee: { status: count } }
    workload = {}
    for r in rows:
        name = r["assignee"]
        status = r["status"].lower()
        if name not in workload:
            workload[name] = {"to do": 0, "in progress": 0, "done": 0}
        
        # Map some statuses to standard buckets if needed
        if "todo" in status or "new" in status or "to do" in status:
            workload[name]["to do"] += r["count"]
        elif "progress" in status or "indeterminate" in status:
            workload[name]["in progress"] += r["count"]
        elif "done" in status:
            workload[name]["done"] += r["count"]
        else:
            workload[name]["to do"] += r["count"] # Default fallback
            
    return {"workload": workload}


@router.get("/dashboard/stale")
async def get_pm_stale_tasks(
    project_key: Optional[str] = None,
    days: int = 3,
    session: AsyncSession = Depends(get_db),
    user: CurrentUser = Depends(get_current_user),
):
    query = """
    SELECT 
        source_id as key,
        title,
        COALESCE(metadata->'assignee'->>'displayName', 'Unassigned') as assignee,
        metadata->>'status' as status_name,
        metadata->>'priority' as priority,
        updated_at,
        url
    FROM documents
    WHERE source = 'jira'
      AND metadata->>'statusCategory' NOT IN ('done')
    """
    
    params = {"days": days}
    if project_key:
        query += " AND (metadata->>'project_key' ILIKE :project_key OR metadata->>'project_key' ILIKE :project_key_br)"
        params["project_key"] = project_key
        params["project_key_br"] = f"[{project_key}]"


        
    # Condition for stale: no update for X days OR High priority
    # Dùng make_interval() thay vì CAST(:days || ' days') để tránh lỗi asyncpg khi truyền int
    query += """
      AND (
          updated_at < NOW() - make_interval(days => :days)
          OR metadata->>'priority' IN ('High', 'Highest')
      )
    """
    
    query += " ORDER BY updated_at ASC LIMIT 15"
    
    res = await session.execute(text(query), params)
    rows = res.mappings().fetchall()
    
    tasks = []
    for r in rows:
        tasks.append({
            "key": r["key"],
            "title": r["title"],
            "assignee": r["assignee"],
            "status": r["status_name"],
            "priority": r["priority"],
            "updated_at": r["updated_at"].isoformat() if r["updated_at"] else None,
            "url": r["url"]
        })
        
    return {"tasks": tasks}
    
@router.post("/dashboard/refresh-ai")
async def refresh_pm_ai_analysis(
    project_key: str,
    session: AsyncSession = Depends(get_db),
    user: CurrentUser = Depends(get_current_user),
):
    """
    Endpoint để PM chủ động kích hoạt AI phân tích rủi ro ngay lập tức.
    Đẩy 1 job vào hàng chờ arq:ai.
    """
    if user.role not in ["pm_po", "system_admin", "admin"]:
        raise HTTPException(status_code=403, detail="Only PMs and Admins can refresh AI analysis")
        
    try:
        from arq_worker import REDIS_URL
        from arq import create_pool
        from arq.connections import RedisSettings
        
        # Kiểm tra xem dự án có dữ liệu Jira không
        res = await session.execute(
            text("SELECT COUNT(*) FROM documents WHERE source = 'jira' AND (metadata->>'project_key' ILIKE :p OR metadata->>'project_key' ILIKE :p_br)"),
            {"p": project_key, "p_br": f"[{project_key}]"}
        )

        count = res.scalar() or 0
        if count == 0:
            raise HTTPException(status_code=404, detail=f"No Jira data found for project {project_key}")

        pool = await create_pool(RedisSettings.from_dsn(REDIS_URL))
        # Enqueue job cụ thể cho project này
        await pool.enqueue_job("generate_pm_digest_job_proxy", project_keys=[project_key], _queue_name="arq:ai")
        
        return {"status": "enqueued", "project": project_key, "message": "AI analysis task has been started. Please refresh after 10-20 seconds."}
    except HTTPException:
        raise
    except Exception as e:
        log.error("pm_routes.refresh_ai.failed", error=str(e))
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/dashboard/burnup")
async def get_pm_burnup(
    project_key: Optional[str] = None,
    session: AsyncSession = Depends(get_db),
    user: CurrentUser = Depends(get_current_user),
):
    query = """
    SELECT 
        DATE(updated_at) as done_date,
        COUNT(id) as count
    FROM documents 
    WHERE source = 'jira' 
      AND metadata->>'statusCategory' = 'done'
    """
    params = {}
    if project_key:
        query += " AND (metadata->>'project_key' ILIKE :project_key OR metadata->>'project_key' ILIKE :project_key_br)"
        params["project_key"] = project_key
        params["project_key_br"] = f"[{project_key}]"
        
    query += " GROUP BY DATE(updated_at) ORDER BY DATE(updated_at) ASC LIMIT 30"
    
    res = await session.execute(text(query), params)
    rows = res.mappings().fetchall()
    
    # Calculate cumulative (Burnup)
    burnup_data = []
    cumulative = 0
    for r in rows:
        cumulative += r["count"]
        burnup_data.append({
            "date": r["done_date"].isoformat() if r["done_date"] else None,
            "daily_completed": r["count"],
            "cumulative": cumulative
        })
        
    return {"burnup": burnup_data}

@router.get("/dashboard/cfd")
async def get_pm_cfd(
    project_key: Optional[str] = None,
    session: AsyncSession = Depends(get_db),
    user: CurrentUser = Depends(get_current_user),
):
    # Simulated CFD from current Snapshot DB
    query = """
    SELECT 
        DATE(created_at) as created_date,
        COUNT(id) as total_entered
    FROM documents 
    WHERE source = 'jira'
    """
    params = {}
    if project_key:
        query += " AND (metadata->>'project_key' ILIKE :project_key OR metadata->>'project_key' ILIKE :project_key_br)"
        params["project_key"] = project_key
        params["project_key_br"] = f"[{project_key}]"
        
    query += " GROUP BY DATE(created_at) ORDER BY DATE(created_at) ASC"
    
    created_res = await session.execute(text(query), params)
    
    # Same for done
    query_done = """
    SELECT 
        DATE(updated_at) as resolved_date,
        COUNT(id) as total_resolved
    FROM documents 
    WHERE source = 'jira' AND metadata->>'statusCategory' = 'done'
    """
    if project_key:
        query_done += " AND (metadata->>'project_key' ILIKE :project_key OR metadata->>'project_key' ILIKE :project_key_br)"
        
    query_done += " GROUP BY DATE(updated_at) ORDER BY DATE(updated_at) ASC"
    
    resolved_res = await session.execute(text(query_done), params)
    
    created_rows = created_res.mappings().fetchall()
    resolved_rows = resolved_res.mappings().fetchall()
    
    timeline = {}
    for r in created_rows:
        d = r["created_date"].isoformat() if r["created_date"] else "unknown"
        if d not in timeline:
             timeline[d] = {"entered": 0, "resolved": 0}
        timeline[d]["entered"] += r["total_entered"]
        
    for r in resolved_rows:
        d = r["resolved_date"].isoformat() if r["resolved_date"] else "unknown"
        if d not in timeline:
             timeline[d] = {"entered": 0, "resolved": 0}
        timeline[d]["resolved"] += r["total_resolved"]
        
    dates = sorted(list(timeline.keys()))
    cfd_data = []
    cum_entered = 0
    cum_resolved = 0
    
    for d in dates:
        if d == "unknown": continue
        cum_entered += timeline[d]["entered"]
        cum_resolved += timeline[d]["resolved"]
        
        # Calculate ToDo + InProgress loosely as entered - resolved
        wip = cum_entered - cum_resolved
        if wip < 0: wip = 0
        
        cfd_data.append({
            "date": d,
            "done": cum_resolved,
            "wip": wip,  # To do + In Progress
            "total": cum_entered
        })
        
    return {"cfd": cfd_data[-30:]} # Last 30 points

@router.get("/dashboard/lead-time")
async def get_pm_lead_time(
    project_key: Optional[str] = None,
    session: AsyncSession = Depends(get_db),
    user: CurrentUser = Depends(get_current_user),
):
    query = """
    SELECT 
        DATE(updated_at) as done_date,
        AVG(EXTRACT(EPOCH FROM (updated_at - created_at))/86400) as daily_avg_lead_time
    FROM documents 
    WHERE source = 'jira' 
      AND metadata->>'statusCategory' = 'done'
      AND updated_at IS NOT NULL
      AND created_at IS NOT NULL
    """
    params = {}
    if project_key:
        query += " AND (metadata->>'project_key' ILIKE :project_key OR metadata->>'project_key' ILIKE :project_key_br)"
        params["project_key"] = project_key
        params["project_key_br"] = f"[{project_key}]"
        
    query += " GROUP BY DATE(updated_at) ORDER BY DATE(updated_at) ASC LIMIT 30"
    
    res = await session.execute(text(query), params)
    rows = res.mappings().fetchall()
    
    overall_avg = 0
    trend = []
    total_days = 0
    count = 0
    for r in rows:
        val = float(r["daily_avg_lead_time"] or 0)
        total_days += val
        count += 1
        trend.append({
            "date": r["done_date"].isoformat() if r["done_date"] else None,
            "avg_lead_time_days": round(val, 2)
        })
        
    if count > 0:
        overall_avg = round(total_days / count, 2)
        
    return {"overall_avg_lead_time_days": overall_avg, "trend": trend}

@router.get("/dashboard/issue-types")
async def get_pm_issue_types(
    project_key: Optional[str] = None,
    session: AsyncSession = Depends(get_db),
    user: CurrentUser = Depends(get_current_user),
):
    query = """
    SELECT 
        COALESCE(metadata->>'issue_type', 'Unknown') as issue_type,
        COUNT(id) as count
    FROM documents 
    WHERE source = 'jira'
    """
    params = {}
    if project_key:
        query += " AND (metadata->>'project_key' ILIKE :project_key OR metadata->>'project_key' ILIKE :project_key_br)"
        params["project_key"] = project_key
        params["project_key_br"] = f"[{project_key}]"
        
    query += " GROUP BY COALESCE(metadata->>'issue_type', 'Unknown') ORDER BY count DESC"
    
    res = await session.execute(text(query), params)
    rows = res.mappings().fetchall()
    
    res_data = [{"type": r["issue_type"], "count": r["count"]} for r in rows]
    return {"issue_types": res_data}

@router.get("/dashboard/epics")
async def get_pm_epics(
    project_key: Optional[str] = None,
    session: AsyncSession = Depends(get_db),
    user: CurrentUser = Depends(get_current_user),
):
    # Fetch Epics
    query = """
    SELECT 
        source_id as key,
        title,
        metadata->>'status' as status_name,
        metadata->>'statusCategory' as status_category,
        updated_at,
        url
    FROM documents
    WHERE source = 'jira'
      AND metadata->>'issue_type' = 'Epic'
    """
    params = {}
    if project_key:
        query += " AND (metadata->>'project_key' ILIKE :project_key OR metadata->>'project_key' ILIKE :project_key_br)"
        params["project_key"] = project_key
        params["project_key_br"] = f"[{project_key}]"
        
    query += " ORDER BY updated_at DESC LIMIT 20"
    
    res = await session.execute(text(query), params)
    rows = res.mappings().fetchall()
    
    epics = []
    for r in rows:
        cat = r["status_category"] or "to do"
        progress = 100 if cat.lower() == 'done' else (50 if cat.lower() in ['in progress', 'indeterminate'] else 0)
        epics.append({
            "key": r["key"],
            "title": r["title"],
            "status": r["status_name"],
            "progress": progress,
            "updated_at": r["updated_at"].isoformat() if r["updated_at"] else None,
            "url": r["url"]
        })
        
    return {"epics": epics}

@router.get("/dashboard/retrospective")
async def get_pm_retrospective(
    project_key: Optional[str] = None,
    limit: int = 2,
    session: AsyncSession = Depends(get_db),
    user: CurrentUser = Depends(get_current_user),
):
    query = """
    SELECT 
        title, content, created_at
    FROM doc_drafts
    WHERE doc_type = 'pm_sprint_retrospective'
    """
    params = {}
    if project_key:
        query += " AND title LIKE :project_key"
        params["project_key"] = f"%[{project_key}]%"
        
    query += " ORDER BY created_at DESC LIMIT :limit"
    params["limit"] = limit
    
    res = await session.execute(text(query), params)
    rows = res.mappings().fetchall()
    
    reports = []
    for r in rows:
        reports.append({
            "title": r["title"],
            "summary": r["content"],
            "created_at": r["created_at"].isoformat() if r["created_at"] else None
        })
        
    if not reports:
        reports = [
            {
                "title": "Chưa có báo cáo AI Retrospective",
                "summary": "AI Retrospective được sinh ra tự động vào cuối mỗi Sprint (TBD).",
                "created_at": None
            }
        ]
        
    return {"retrospectives": reports}


class CustomReportRequest(BaseModel):
    project_key: str
    prompt: str

@router.post("/dashboard/custom-report")
async def generate_pm_custom_report(
    req: CustomReportRequest,
    session: AsyncSession = Depends(get_db),
    user: CurrentUser = Depends(get_current_user),
):
    project_key = req.project_key.strip()
    prompt = req.prompt.strip()
    
    if not project_key or not prompt:
        raise HTTPException(status_code=400, detail="Missing project_key or prompt")
        
    # Fetch recent data for context (limit 150)
    query = """
    SELECT 
        source_id as key,
        title,
        metadata->>'status' as status,
        metadata->>'priority' as priority,
        metadata->>'issue_type' as issue_type,
        COALESCE(metadata->'assignee'->>'displayName', 'Unassigned') as assignee,
        DATE(created_at) as created_at,
        DATE(updated_at) as updated_at
    FROM documents
    WHERE source = 'jira'
      AND (metadata->>'project_key' ILIKE :project_key OR metadata->>'project_key' ILIKE :project_key_br)
    ORDER BY updated_at DESC LIMIT 150
    """
    
    params = {
        "project_key": project_key,
        "project_key_br": f"[{project_key}]"
    }
    
    res = await session.execute(text(query), params)
    rows = res.mappings().fetchall()
    
    if not rows:
        raise HTTPException(status_code=404, detail=f"Không tìm thấy data Jira cho dự án {project_key}")
        
    context_lines = []
    for r in rows:
        context_lines.append(f"[{r['key']}] {r['title']} | Status: {r['status']} | Type: {r['issue_type']} | Priority: {r['priority']} | Assignee: {r['assignee']} | Updated: {r['updated_at']}")
        
    context_str = "\n".join(context_lines)
    
    system_prompt = f"""Bạn là một Chuyên gia Quản lý Dự án (PM/PO) AI cao cấp. Phân tích Dữ liệu Dự án Jira bên dưới để tạo Báo cáo Markdown trả lời yêu cầu của Người Dùng. 

DỮ LIỆU DỰ ÁN ({project_key}):
{context_str}

QUY TẮC PHẢN HỒI:
1. Bạn phải phân tích Dữ liệu Dự án để trả lời. Không bịa đặt data. 
2. Trả lời bằng định dạng Markdown đẹp, chuyên nghiệp.
3. Nếu Người Dùng yêu cầu hoặc câu trả lời phù hợp để vẽ biểu đồ Tỷ lệ (Pie/Doughnut), Số lượng (Bar), hoặc Xu hướng (Line), HÃY XUẤT RA MỘT KHỐI JSON CHỨA CẤU HÌNH CHART.JS chuẩn xác.
4. Cú pháp bắt buộc để xuất biểu đồ là:
```json
{{
  "is_chart": true,
  "type": "bar", // bar, line, pie, doughnut
  "data": {{
      "labels": ["Item 1", "Item 2"],
      "datasets": [{{ "label": "Dataset 1", "data": [10, 20], "backgroundColor": ["#3b82f6", "#ef4444"] }}]
  }},
  "options": {{ "responsive": true }}
}}
```
Khối JSON phải nằm gọn trong cặp ```json ... ``` (để render frontend bắt được). Đảm bảo JSON hợp lệ 100%. Mảng màu tham khảo: #3b82f6, #ef4444, #10b981, #f59e0b, #8b5cf6, #64748b."""

    llm = LLMService(task_type="pm_report")
    try:
        reply = await llm.chat(system=system_prompt, user=f"Yêu cầu của bạn: {prompt}", max_tokens=1500)
        return {"report": reply}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"LLM Error: {str(e)}")

