from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession
from typing import Optional
import json
from pydantic import BaseModel
from services.llm_service import LLMService

from apps.api.auth.dependencies import CurrentUser, get_current_user
from storage.db.db import get_db
from connectors.jira.jira_client import JiraClient

router = APIRouter(prefix="/pm", tags=["pm_dashboard"])

@router.get("/projects")
async def get_pm_projects(
    session: AsyncSession = Depends(get_db),
    user: CurrentUser = Depends(get_current_user),
):
    try:
        # Fetching directly from Jira Client (or we can query distinct 'project' from documents)
        client = JiraClient()
        projects = client.get_projects()
        
        return {
            "projects": [
                {
                    "key": p.get("key"), 
                    "name": p.get("name"),
                    "id": p.get("id"),
                    "avatar": p.get("avatarUrls", {}).get("48x48")
                } 
                for p in projects
            ]
        }
    except Exception as e:
        # Fallback to DB if live Jira connection fails
        res = await session.execute(text("SELECT DISTINCT metadata->>'project' as key FROM documents WHERE source='jira' AND metadata->>'project' IS NOT NULL"))
        projects = [{"key": row[0], "name": row[0]} for row in res.fetchall()]
        return {"projects": projects}


@router.get("/dashboard/stats")
async def get_pm_dashboard_stats(
    project_key: Optional[str] = None,
    session: AsyncSession = Depends(get_db),
    user: CurrentUser = Depends(get_current_user),
):
    # Fetching metrics from pm_metrics_daily and pm_project_insights
    query_metrics = text("""
        SELECT 
            todo_count, in_progress_count, done_count, high_priority_count
        FROM pm_metrics_daily
        WHERE (:p IS NULL OR project_key = :p)
        ORDER BY date DESC LIMIT 1
    """)
    
    query_insights = text("""
        SELECT velocity_weekly, risk_score, health_status, insight
        FROM pm_metrics_by_project
        WHERE (:p IS NULL OR project_key = :p)
        ORDER BY updated_at DESC LIMIT 1
    """)
    
    d_res = await session.execute(query_metrics, {"p": project_key})
    d_metrics = d_res.mappings().first()
    
    p_res = await session.execute(query_insights, {"p": project_key})
    p_metrics = p_res.mappings().first()
    
    return {
        "project_key": project_key,
        "velocity_weekly": p_metrics["velocity_weekly"] if p_metrics else 0,
        "risk_score": p_metrics["risk_score"] if p_metrics else 0,
        "health_status": p_metrics["health_status"] if p_metrics else "healthy",
        "insight": p_metrics["insight"] if p_metrics else None,
        "total_issues": (d_metrics["todo_count"] + d_metrics["in_progress_count"] + d_metrics["done_count"]) if d_metrics else 0,
        "done_issues": d_metrics["done_count"] if d_metrics else 0,
        "in_progress_issues": d_metrics["in_progress_count"] if d_metrics else 0,
        "todo_issues": d_metrics["todo_count"] if d_metrics else 0,
        "high_priority_issues": d_metrics["high_priority_count"] if d_metrics else 0,
        "completion_rate": round((d_metrics["done_count"] / (d_metrics["todo_count"] + d_metrics["in_progress_count"] + d_metrics["done_count"]) * 100), 1) if d_metrics and (d_metrics["todo_count"] + d_metrics["in_progress_count"] + d_metrics["done_count"]) > 0 else 0
    }
    
@router.get("/dashboard/risks")
async def get_pm_risks(
    project_key: Optional[str] = None,
    limit: int = 5,
    session: AsyncSession = Depends(get_db),
    user: CurrentUser = Depends(get_current_user),
):
    # Placeholder for risks generated by PM Digest background task
    # For now, we simulate pulling "ai_task_drafts" or "documents" that are labeled as risks
    # In full implementation, we can query a specific table for generated reports
    
    query = """
    SELECT 
        title, content, created_at
    FROM doc_drafts
    WHERE doc_type = 'pm_risk_report'
    """
    
    params = {}
    if project_key:
        query += " AND title LIKE :project_key"
        params["project_key"] = f"%[{project_key}]%"
        
    query += " ORDER BY created_at DESC LIMIT :limit"
    params["limit"] = limit
    
    res = await session.execute(text(query), params)
    rows = res.mappings().fetchall()
    
    risks = []
    for r in rows:
        risks.append({
            "title": r["title"],
            "summary": r["content"],
            "created_at": r["created_at"].isoformat() if r["created_at"] else None
        })
        
    # If no AI reports generated yet, send dummy data just for the UI
    if not risks:
        risks = [
            {
                "title": "Chưa có báo cáo AI",
                "summary": "Hệ thống tự động (PM Digest) chưa chạy cho dự án này. Báo cáo sẽ được tạo vào 8:00 AM Thứ Hai và Thứ Năm.",
                "created_at": None
            }
        ]
        
    return {"risks": risks}

@router.get("/dashboard/workload")
async def get_pm_workload(
    project_key: Optional[str] = None,
    session: AsyncSession = Depends(get_db),
    user: CurrentUser = Depends(get_current_user),
):
    query = "SELECT user_id, display_name, project_key, todo_count, in_progress_count, done_count FROM pm_metrics_by_user"
    params = {}
    if project_key:
        query += " WHERE project_key = :p"
        params["p"] = project_key
        
    res = await session.execute(text(query), params)
    rows = res.mappings().fetchall()
    
    workload = {}
    for r in rows:
        name = r["display_name"] or r["user_id"]
        if name not in workload:
            workload[name] = {"to do": 0, "in progress": 0, "done": 0}
        workload[name]["to do"] += r["todo_count"]
        workload[name]["in progress"] += r["in_progress_count"]
        workload[name]["done"] += r["done_count"]
            
    return {"workload": workload}


@router.get("/dashboard/stale")
async def get_pm_stale_tasks(
    project_key: Optional[str] = None,
    days: int = 3,
    session: AsyncSession = Depends(get_db),
    user: CurrentUser = Depends(get_current_user),
):
    res = await session.execute(text(query), params)
    rows = res.mappings().fetchall()
    return {"tasks": [dict(r) for r in rows]}
    
@router.post("/dashboard/refresh-ai")
async def refresh_pm_ai_analysis(
    project_key: str,
    session: AsyncSession = Depends(get_db),
    user: CurrentUser = Depends(get_current_user),
):
    """
    Endpoint để PM chủ động kích hoạt AI phân tích rủi ro ngay lập tức.
    Đẩy 1 job vào hàng chờ arq:ai.
    """
    if user.role not in ["pm_po", "system_admin", "admin"]:
        raise HTTPException(status_code=403, detail="Only PMs and Admins can refresh AI analysis")
        
    try:
        from arq_worker import REDIS_URL
        from arq import create_pool
        from arq.connections import RedisSettings
        
        # Kiểm tra xem dự án có dữ liệu Jira không
        res = await session.execute(
            text("SELECT COUNT(*) FROM documents WHERE source = 'jira' AND (metadata->>'project_key' ILIKE :p OR metadata->>'project_key' ILIKE :p_br)"),
            {"p": project_key, "p_br": f"[{project_key}]"}
        )

        count = res.scalar() or 0
        if count == 0:
            raise HTTPException(status_code=404, detail=f"No Jira data found for project {project_key}")

        pool = await create_pool(RedisSettings.from_dsn(REDIS_URL))
        # Enqueue job cụ thể cho project này
        await pool.enqueue_job("generate_pm_digest_job_proxy", project_keys=[project_key], _queue_name="arq:ai")
        
        return {"status": "enqueued", "project": project_key, "message": "AI analysis task has been started. Please refresh after 10-20 seconds."}
    except HTTPException:
        raise
    except Exception as e:
        log.error("pm_routes.refresh_ai.failed", error=str(e))
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/dashboard/burnup")
async def get_pm_burnup(
    project_key: Optional[str] = None,
    session: AsyncSession = Depends(get_db),
    user: CurrentUser = Depends(get_current_user),
):
    query = """
    SELECT 
        DATE(updated_at) as done_date,
        COUNT(id) as count
    FROM documents 
    WHERE source = 'jira' 
      AND metadata->>'statusCategory' = 'done'
    """
    params = {}
    if project_key:
        query += " AND (metadata->>'project_key' ILIKE :project_key OR metadata->>'project_key' ILIKE :project_key_br)"
        params["project_key"] = project_key
        params["project_key_br"] = f"[{project_key}]"
        
    query += " GROUP BY DATE(updated_at) ORDER BY DATE(updated_at) ASC LIMIT 30"
    
    res = await session.execute(text(query), params)
    rows = res.mappings().fetchall()
    
    # Calculate cumulative (Burnup)
    burnup_data = []
    cumulative = 0
    for r in rows:
        cumulative += r["count"]
        burnup_data.append({
            "date": r["done_date"].isoformat() if r["done_date"] else None,
            "daily_completed": r["count"],
            "cumulative": cumulative
        })
        
    return {"burnup": burnup_data}

@router.get("/dashboard/cfd")
async def get_pm_cfd(
    project_key: Optional[str] = None,
    session: AsyncSession = Depends(get_db),
    user: CurrentUser = Depends(get_current_user),
):
    # Simulated CFD from current Snapshot DB
    query = """
    SELECT 
        DATE(created_at) as created_date,
        COUNT(id) as total_entered
    FROM documents 
    WHERE source = 'jira'
    """
    params = {}
    if project_key:
        query += " AND (metadata->>'project_key' ILIKE :project_key OR metadata->>'project_key' ILIKE :project_key_br)"
        params["project_key"] = project_key
        params["project_key_br"] = f"[{project_key}]"
        
    query += " GROUP BY DATE(created_at) ORDER BY DATE(created_at) ASC"
    
    created_res = await session.execute(text(query), params)
    
    # Same for done
    query_done = """
    SELECT 
        DATE(updated_at) as resolved_date,
        COUNT(id) as total_resolved
    FROM documents 
    WHERE source = 'jira' AND metadata->>'statusCategory' = 'done'
    """
    if project_key:
        query_done += " AND (metadata->>'project_key' ILIKE :project_key OR metadata->>'project_key' ILIKE :project_key_br)"
        
    query_done += " GROUP BY DATE(updated_at) ORDER BY DATE(updated_at) ASC"
    
    resolved_res = await session.execute(text(query_done), params)
    
    created_rows = created_res.mappings().fetchall()
    resolved_rows = resolved_res.mappings().fetchall()
    
    timeline = {}
    for r in created_rows:
        d = r["created_date"].isoformat() if r["created_date"] else "unknown"
        if d not in timeline:
             timeline[d] = {"entered": 0, "resolved": 0}
        timeline[d]["entered"] += r["total_entered"]
        
    for r in resolved_rows:
        d = r["resolved_date"].isoformat() if r["resolved_date"] else "unknown"
        if d not in timeline:
             timeline[d] = {"entered": 0, "resolved": 0}
        timeline[d]["resolved"] += r["total_resolved"]
        
    dates = sorted(list(timeline.keys()))
    cfd_data = []
    cum_entered = 0
    cum_resolved = 0
    
    for d in dates:
        if d == "unknown": continue
        cum_entered += timeline[d]["entered"]
        cum_resolved += timeline[d]["resolved"]
        
        # Calculate ToDo + InProgress loosely as entered - resolved
        wip = cum_entered - cum_resolved
        if wip < 0: wip = 0
        
        cfd_data.append({
            "date": d,
            "done": cum_resolved,
            "wip": wip,  # To do + In Progress
            "total": cum_entered
        })
        
    return {"cfd": cfd_data[-30:]} # Last 30 points

@router.get("/dashboard/lead-time")
async def get_pm_lead_time(
    project_key: Optional[str] = None,
    session: AsyncSession = Depends(get_db),
    user: CurrentUser = Depends(get_current_user),
):
    query = """
    SELECT 
        DATE(updated_at) as done_date,
        AVG(EXTRACT(EPOCH FROM (updated_at - created_at))/86400) as daily_avg_lead_time
    FROM documents 
    WHERE source = 'jira' 
      AND metadata->>'statusCategory' = 'done'
      AND updated_at IS NOT NULL
      AND created_at IS NOT NULL
    """
    params = {}
    if project_key:
        query += " AND (metadata->>'project_key' ILIKE :project_key OR metadata->>'project_key' ILIKE :project_key_br)"
        params["project_key"] = project_key
        params["project_key_br"] = f"[{project_key}]"
        
    query += " GROUP BY DATE(updated_at) ORDER BY DATE(updated_at) ASC LIMIT 30"
    
    res = await session.execute(text(query), params)
    rows = res.mappings().fetchall()
    
    overall_avg = 0
    trend = []
    total_days = 0
    count = 0
    for r in rows:
        val = float(r["daily_avg_lead_time"] or 0)
        total_days += val
        count += 1
        trend.append({
            "date": r["done_date"].isoformat() if r["done_date"] else None,
            "avg_lead_time_days": round(val, 2)
        })
        
    if count > 0:
        overall_avg = round(total_days / count, 2)
        
    return {"overall_avg_lead_time_days": overall_avg, "trend": trend}

@router.get("/dashboard/issue-types")
async def get_pm_issue_types(
    project_key: Optional[str] = None,
    session: AsyncSession = Depends(get_db),
    user: CurrentUser = Depends(get_current_user),
):
    query = """
    SELECT 
        COALESCE(metadata->>'issue_type', 'Unknown') as issue_type,
        COUNT(id) as count
    FROM documents 
    WHERE source = 'jira'
    """
    params = {}
    if project_key:
        query += " AND (metadata->>'project_key' ILIKE :project_key OR metadata->>'project_key' ILIKE :project_key_br)"
        params["project_key"] = project_key
        params["project_key_br"] = f"[{project_key}]"
        
    query += " GROUP BY COALESCE(metadata->>'issue_type', 'Unknown') ORDER BY count DESC"
    
    res = await session.execute(text(query), params)
    rows = res.mappings().fetchall()
    
    res_data = [{"type": r["issue_type"], "count": r["count"]} for r in rows]
    return {"issue_types": res_data}

@router.get("/dashboard/epics")
async def get_pm_epics(
    project_key: Optional[str] = None,
    session: AsyncSession = Depends(get_db),
    user: CurrentUser = Depends(get_current_user),
):
    # Fetch Epics
    query = """
    SELECT 
        source_id as key,
        title,
        metadata->>'status' as status_name,
        metadata->>'statusCategory' as status_category,
        updated_at,
        url
    FROM documents
    WHERE source = 'jira'
      AND metadata->>'issue_type' = 'Epic'
    """
    params = {}
    if project_key:
        query += " AND (metadata->>'project_key' ILIKE :project_key OR metadata->>'project_key' ILIKE :project_key_br)"
        params["project_key"] = project_key
        params["project_key_br"] = f"[{project_key}]"
        
    query += " ORDER BY updated_at DESC LIMIT 20"
    
    res = await session.execute(text(query), params)
    rows = res.mappings().fetchall()
    
    epics = []
    for r in rows:
        cat = r["status_category"] or "to do"
        progress = 100 if cat.lower() == 'done' else (50 if cat.lower() in ['in progress', 'indeterminate'] else 0)
        epics.append({
            "key": r["key"],
            "title": r["title"],
            "status": r["status_name"],
            "progress": progress,
            "updated_at": r["updated_at"].isoformat() if r["updated_at"] else None,
            "url": r["url"]
        })
        
    return {"epics": epics}

@router.get("/dashboard/retrospective")
async def get_pm_retrospective(
    project_key: Optional[str] = None,
    limit: int = 2,
    session: AsyncSession = Depends(get_db),
    user: CurrentUser = Depends(get_current_user),
):
    query = """
    SELECT 
        title, content, created_at
    FROM doc_drafts
    WHERE doc_type = 'pm_sprint_retrospective'
    """
    params = {}
    if project_key:
        query += " AND title LIKE :project_key"
        params["project_key"] = f"%[{project_key}]%"
        
    query += " ORDER BY created_at DESC LIMIT :limit"
    params["limit"] = limit
    
    res = await session.execute(text(query), params)
    rows = res.mappings().fetchall()
    
    reports = []
    for r in rows:
        reports.append({
            "title": r["title"],
            "summary": r["content"],
            "created_at": r["created_at"].isoformat() if r["created_at"] else None
        })
        
    if not reports:
        reports = [
            {
                "title": "Chưa có báo cáo AI Retrospective",
                "summary": "AI Retrospective được sinh ra tự động vào cuối mỗi Sprint (TBD).",
                "created_at": None
            }
        ]
        
    return {"retrospectives": reports}


class CustomReportRequest(BaseModel):
    project_key: str
    prompt: str

@router.post("/dashboard/custom-report")
async def generate_pm_custom_report(
    req: CustomReportRequest,
    session: AsyncSession = Depends(get_db),
    user: CurrentUser = Depends(get_current_user),
):
    project_key = req.project_key.strip()
    prompt = req.prompt.strip()
    
    if not project_key or not prompt:
        raise HTTPException(status_code=400, detail="Missing project_key or prompt")
        
    # Fetch current metrics for AI analysis
    metrics_query = """
    SELECT 
        p.velocity_weekly, p.velocity_delta_pct, p.risk_score, p.health_status,
        d.todo_count, d.in_progress_count, d.done_count
    FROM pm_metrics_by_project p
    JOIN pm_metrics_daily d ON d.project_key = p.project_key
    WHERE p.project_key = :p
    ORDER BY d.date DESC LIMIT 1
    """
    m_res = await session.execute(text(metrics_query), {"p": project_key})
    m = m_res.mappings().first() or {}
    
    metrics_summary = f"""
    THỐNG KÊ HIỆN TẠI:
    - Velocity tuần này: {m.get('velocity_weekly', 0)} task
    - So với tuần trước: {m.get('velocity_delta_pct', 0)}%
    - Chỉ số rủi ro: {m.get('risk_score', 0)}/100
    - Trạng thái: {m.get('health_status', 'N/A')}
    - Phân bổ: ToDo({m.get('todo_count',0)}), InProgress({m.get('in_progress_count',0)}), Done({m.get('done_count',0)})
    """

    system_prompt = f"""Bạn là một Chuyên gia Quản lý Dự án AI. Phân tích Dữ liệu Dự án Jira bên dưới để tạo Báo cáo Markdown trả lời yêu cầu của Người Dùng. 

DỮ LIỆU DỰ ÁN ({project_key}):
{metrics_summary}

{context_str}

QUY TẮC PHẢN HỒI:
1. Bạn phải dựa trên con số cụ thể trong THỐNG KÊ HIỆN TẠI để giải thích. Không nói chung chung. 
Ví dụ: "Dự án chậm do Velocity giảm 15% so với tuần trước và 80% task đang bị nghẽn (In Progress > 3 ngày)".
2. Phải đưa ra nhận định PM sắc bén: Team nào bottleneck? Sprint này ổn hay trễ? Cần xử lý ngay task nào?
3. Trả lời bằng Markdown chuyên nghiệp.
4. Xuất biểu đồ JSON nếu cần (Pie/Bar/Line)."""

    llm = LLMService(task_type="pm_report")
    try:
        reply = await llm.chat(system=system_prompt, user=f"Yêu cầu: {prompt}", max_tokens=1500)
        return {"report": reply}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"LLM Error: {str(e)}")


@router.get("/dashboard/at-risk")
async def get_at_risk_projects(
    session: AsyncSession = Depends(get_db),
    user: CurrentUser = Depends(get_current_user),
):
    query = "SELECT * FROM pm_metrics_by_project WHERE health_status != 'healthy' ORDER BY risk_score DESC LIMIT 5"
    res = await session.execute(text(query))
    return {"projects": [dict(r) for r in res.mappings().fetchall()]}


@router.get("/dashboard/details")
async def get_pm_drilldown(
    metric: str,
    project_key: Optional[str] = None,
    session: AsyncSession = Depends(get_db),
    user: CurrentUser = Depends(get_current_user),
):
    """Drill-down API to fetch issue list for a specific metric."""
    query = """
    SELECT 
        source_id as key, title, 
        metadata->>'status' as status, 
        metadata->'assignee'->>'displayName' as assignee, 
        url
    FROM documents
    WHERE source = 'jira'
    """
    params = {}
    if project_key:
        query += " AND metadata->>'project_key' = :p"
        params["p"] = project_key
        
    if metric == "high_priority":
        query += " AND metadata->>'priority' IN ('High', 'Highest')"
    elif metric == "todo":
        query += " AND metadata->>'statusCategory' = 'to do'"
    elif metric == "in_progress":
        query += " AND metadata->>'statusCategory' = 'in progress'"
    elif metric == "done":
        query += " AND metadata->>'statusCategory' = 'done'"
    elif metric == "stale":
        query += " AND metadata->>'statusCategory' = 'in progress' AND updated_at < NOW() - interval '3 days'"
        
    query += " LIMIT 50"
    res = await session.execute(text(query), params)
    return {"issues": [dict(r) for r in res.mappings().fetchall()]}

