from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession
from typing import Optional

from apps.api.auth.dependencies import CurrentUser, get_current_user
from storage.db.db import get_db
from connectors.jira.jira_client import JiraClient

router = APIRouter(prefix="/pm", tags=["pm_dashboard"])

@router.get("/projects")
async def get_pm_projects(
    session: AsyncSession = Depends(get_db),
    user: CurrentUser = Depends(get_current_user),
):
    try:
        # Fetching directly from Jira Client (or we can query distinct 'project' from documents)
        client = JiraClient()
        projects = client.get_projects()
        
        return {
            "projects": [
                {
                    "key": p.get("key"), 
                    "name": p.get("name"),
                    "id": p.get("id"),
                    "avatar": p.get("avatarUrls", {}).get("48x48")
                } 
                for p in projects
            ]
        }
    except Exception as e:
        # Fallback to DB if live Jira connection fails
        res = await session.execute(text("SELECT DISTINCT metadata->>'project' as key FROM documents WHERE source='jira' AND metadata->>'project' IS NOT NULL"))
        projects = [{"key": row[0], "name": row[0]} for row in res.fetchall()]
        return {"projects": projects}


@router.get("/dashboard/stats")
async def get_pm_dashboard_stats(
    project_key: Optional[str] = None,
    session: AsyncSession = Depends(get_db),
    user: CurrentUser = Depends(get_current_user),
):
    # Base query for all Jira documents
    query = """
    SELECT 
        COUNT(id) as total_issues,
        COUNT(id) FILTER (WHERE metadata->>'statusCategory' = 'done') as done_issues,
        COUNT(id) FILTER (WHERE metadata->>'statusCategory' IN ('in progress', 'indeterminate')) as in_progress_issues,
        COUNT(id) FILTER (WHERE metadata->>'statusCategory' IN ('to do', 'new')) as todo_issues,
        COUNT(id) FILTER (WHERE metadata->>'priority' IN ('High', 'Highest')) as high_priority_issues
    FROM documents 
    WHERE source = 'jira'
    """
    
    params = {}
    if project_key:
        query += " AND (metadata->>'project_key' ILIKE :project_key OR metadata->>'project_key' ILIKE :project_key_br)"
        params["project_key"] = project_key
        params["project_key_br"] = f"[{project_key}]"


        
    res = await session.execute(text(query), params)
    row = res.mappings().first()
    
    if not row:
         return {
            "total_issues": 0, "done_issues": 0, 
            "in_progress_issues": 0, "todo_issues": 0, "high_priority_issues": 0,
            "completion_rate": 0
         }
         
    total = row["total_issues"] or 0
    done = row["done_issues"] or 0
    in_progress = row["in_progress_issues"] or 0
    todo = row["todo_issues"] or 0
    high_priority = row["high_priority_issues"] or 0
    
    completion_rate = round((done / total * 100), 2) if total > 0 else 0
    
    return {
        "total_issues": total,
        "done_issues": done,
        "in_progress_issues": in_progress,
        "todo_issues": todo,
        "high_priority_issues": high_priority,
        "completion_rate": completion_rate
    }
    
@router.get("/dashboard/risks")
async def get_pm_risks(
    project_key: Optional[str] = None,
    limit: int = 5,
    session: AsyncSession = Depends(get_db),
    user: CurrentUser = Depends(get_current_user),
):
    # Placeholder for risks generated by PM Digest background task
    # For now, we simulate pulling "ai_task_drafts" or "documents" that are labeled as risks
    # In full implementation, we can query a specific table for generated reports
    
    query = """
    SELECT 
        title, content, created_at
    FROM doc_drafts
    WHERE doc_type = 'pm_risk_report'
    """
    
    params = {}
    if project_key:
        query += " AND title LIKE :project_key"
        params["project_key"] = f"%[{project_key}]%"
        
    query += " ORDER BY created_at DESC LIMIT :limit"
    params["limit"] = limit
    
    res = await session.execute(text(query), params)
    rows = res.mappings().fetchall()
    
    risks = []
    for r in rows:
        risks.append({
            "title": r["title"],
            "summary": r["content"],
            "created_at": r["created_at"].isoformat() if r["created_at"] else None
        })
        
    # If no AI reports generated yet, send dummy data just for the UI
    if not risks:
        risks = [
            {
                "title": "Chưa có báo cáo AI",
                "summary": "Hệ thống tự động (PM Digest) chưa chạy cho dự án này. Báo cáo sẽ được tạo vào 8:00 AM Thứ Hai và Thứ Năm.",
                "created_at": None
            }
        ]
        
    return {"risks": risks}

@router.get("/dashboard/workload")
async def get_pm_workload(
    project_key: Optional[str] = None,
    session: AsyncSession = Depends(get_db),
    user: CurrentUser = Depends(get_current_user),
):
    query = """
    SELECT 
        COALESCE(metadata->'assignee'->>'displayName', 'Unassigned') as assignee,
        COALESCE(metadata->>'statusCategory', 'to do') as status,
        COUNT(*) as count
    FROM documents
    WHERE source = 'jira'
    """
    
    params = {}
    if project_key:
        query += " AND (metadata->>'project_key' ILIKE :project_key OR metadata->>'project_key' ILIKE :project_key_br)"
        params["project_key"] = project_key
        params["project_key_br"] = f"[{project_key}]"


        
    query += " GROUP BY 1, 2 ORDER BY count DESC"
    
    res = await session.execute(text(query), params)
    rows = res.mappings().fetchall()
    
    # Structure data for Chart.js: { assignee: { status: count } }
    workload = {}
    for r in rows:
        name = r["assignee"]
        status = r["status"].lower()
        if name not in workload:
            workload[name] = {"to do": 0, "in progress": 0, "done": 0}
        
        # Map some statuses to standard buckets if needed
        if "todo" in status or "new" in status or "to do" in status:
            workload[name]["to do"] += r["count"]
        elif "progress" in status or "indeterminate" in status:
            workload[name]["in progress"] += r["count"]
        elif "done" in status:
            workload[name]["done"] += r["count"]
        else:
            workload[name]["to do"] += r["count"] # Default fallback
            
    return {"workload": workload}


@router.get("/dashboard/stale")
async def get_pm_stale_tasks(
    project_key: Optional[str] = None,
    days: int = 3,
    session: AsyncSession = Depends(get_db),
    user: CurrentUser = Depends(get_current_user),
):
    query = """
    SELECT 
        source_id as key,
        title,
        COALESCE(metadata->'assignee'->>'displayName', 'Unassigned') as assignee,
        metadata->>'status' as status_name,
        metadata->>'priority' as priority,
        updated_at,
        url
    FROM documents
    WHERE source = 'jira'
      AND metadata->>'statusCategory' NOT IN ('done')
    """
    
    params = {"days": days}
    if project_key:
        query += " AND (metadata->>'project_key' ILIKE :project_key OR metadata->>'project_key' ILIKE :project_key_br)"
        params["project_key"] = project_key
        params["project_key_br"] = f"[{project_key}]"


        
    # Condition for stale: no update for X days OR High priority
    # Dùng make_interval() thay vì CAST(:days || ' days') để tránh lỗi asyncpg khi truyền int
    query += """
      AND (
          updated_at < NOW() - make_interval(days => :days)
          OR metadata->>'priority' IN ('High', 'Highest')
      )
    """
    
    query += " ORDER BY updated_at ASC LIMIT 15"
    
    res = await session.execute(text(query), params)
    rows = res.mappings().fetchall()
    
    tasks = []
    for r in rows:
        tasks.append({
            "key": r["key"],
            "title": r["title"],
            "assignee": r["assignee"],
            "status": r["status_name"],
            "priority": r["priority"],
            "updated_at": r["updated_at"].isoformat() if r["updated_at"] else None,
            "url": r["url"]
        })
        
    return {"tasks": tasks}
    
@router.post("/dashboard/refresh-ai")
async def refresh_pm_ai_analysis(
    project_key: str,
    session: AsyncSession = Depends(get_db),
    user: CurrentUser = Depends(get_current_user),
):
    """
    Endpoint để PM chủ động kích hoạt AI phân tích rủi ro ngay lập tức.
    Đẩy 1 job vào hàng chờ arq:ai.
    """
    if user.role not in ["pm_po", "system_admin", "admin"]:
        raise HTTPException(status_code=403, detail="Only PMs and Admins can refresh AI analysis")
        
    try:
        from arq_worker import REDIS_URL
        from arq import create_pool
        from arq.connections import RedisSettings
        
        # Kiểm tra xem dự án có dữ liệu Jira không
        res = await session.execute(
            text("SELECT COUNT(*) FROM documents WHERE source = 'jira' AND (metadata->>'project_key' ILIKE :p OR metadata->>'project_key' ILIKE :p_br)"),
            {"p": project_key, "p_br": f"[{project_key}]"}
        )

        count = res.scalar() or 0
        if count == 0:
            raise HTTPException(status_code=404, detail=f"No Jira data found for project {project_key}")

        pool = await create_pool(RedisSettings.from_dsn(REDIS_URL))
        # Enqueue job cụ thể cho project này
        await pool.enqueue_job("generate_pm_digest_job_proxy", project_keys=[project_key], _queue_name="arq:ai")
        
        return {"status": "enqueued", "project": project_key, "message": "AI analysis task has been started. Please refresh after 10-20 seconds."}
    except HTTPException:
        raise
    except Exception as e:
        log.error("pm_routes.refresh_ai.failed", error=str(e))
        raise HTTPException(status_code=500, detail=str(e))

